project:
  type: website
  output-dir: _site

website:
  title: "Yong's Blog"
  navbar:
    left:
      - file: hello.ipynb
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


