project:
  type: website
  output-dir: _site

website:
  title: "Yong's Blog"
  navbar:
    left:
      - href: hello.ipynb
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

publish:
  provider: gh-pages

